# Site settings
email:
baseurl: ""
paginate: 5
paginate_path: "/blog/page-:num"
google_analytics:

# SEO settings
title: jenleebell
description:
url: ""
twitter_username:
default_img:

# Profile settings
name: Jennifer Lee Bell
profile_img: http://jenleebell.com/img/mika.jpg
profile:
social:
  github: https://github.com/jenleebell

# Build settings
exclude: ["_screenshots", "Gemfile", "Gemfile.lock", "LICENSE.txt", "README.md"]
markdown: kramdown
permalink: /:year/:month/:day/:title/

# Sass
sass:
  style: compressed

# Gems
gems: [jekyll-paginate, jekyll-sitemap, octopress-autoprefixer]
